name: Criar Chave SSH, Import AWS e GIthub

on:
  push:
    branches:
      - main
    
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  LATEST_IMAGE_TAG: ${{ secrets.LATEST_IMAGE_TAG }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 


jobs:
  create_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Criar SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -C "claudio.fe.rejes@gmail.com" -f /tmp/deploy_key -N ''
          ls -lha /tmp
          sudo apt-get update
          sudo apt-get install -y awscli tree
          tree /tmp
          cd /tmp
          aws ec2 import-key-pair --key-name deploy_key --public-key-material file:deploy_key.pub
          echo "SSH_PRIVATE_KEY=$(cat /tmp/deploy_key)" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY_PATH=/tmp/deploy_key" >> $GITHUB_ENV
