name: Criar Chave SSH, Import AWS e GitHub

on:
  push:
    branches:
      - main
    
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  LATEST_IMAGE_TAG: ${{ secrets.LATEST_IMAGE_TAG }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 

jobs:
  create_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Criar SSH Key
        run: ssh-keygen -t rsa -b 4096 -C "claudio.fe.rejes@gmail.com" -f deploy_key -N ''

      - name: Mover a chave para o diretório de trabalho
        run: mv deploy_key.pem $GITHUB_WORKSPACE/

  import_ssh_key_to_aws:
    needs: create_ssh_key
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Import SSH Key to AWS
        run: |
          aws ec2 import-key-pair --key-name ec2-container-key --public-key-material file://$GITHUB_WORKSPACE/deploy_key.pub

  add_ssh_key_to_github_secrets:
    needs: import_ssh_key_to_aws
    runs-on: ubuntu-latest
    steps:
      - name: Configurar GitHub Environment Variables
        run: |
          echo "SSH_PRIVATE_KEY=$(cat $GITHUB_WORKSPACE/deploy_key.pem)" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY_PATH=$GITHUB_WORKSPACE/deploy_key.pem" >> $GITHUB_ENV

  cleanup:
    runs-on: ubuntu-latest
    needs: [add_ssh_key_to_github_secrets]
    steps:
      - name: Remover a chave SSH
        run: rm $GITHUB_WORKSPACE/deploy_key.pem
