name: Terraform APPLY - Infra_LAB_Globo
on: 
  workflow_dispatch:
    inputs:
      wait-time:
        description:  'Tempo de espera para inicar o Apply: 2m, 3m, 5m'
        required:  true
        default: '3m'

env: 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  LATEST_IMAGE_TAG: ${{secrets.LATEST_IMAGE_TAG}}

jobs:
  terraform:
    runs-on:  ubuntu-22.04
    steps:

      - name: Instalar Terraform and Tools
        run: |
          cd ~
          sudo apt update
          sudo apt install -y unzip wget tree
          sudo wget https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
          ls -lha
          sudo unzip terraform_1.5.5_linux_amd64.zip
          sudo chmod +x terraform
          sudo cp -r terraform /usr/local/bin
          ls -lh /usr/local/bin
      
      - name:  Repositorio Terraform
        uses: actions/checkout@v2
        with:
          ref: main
          path: ./repository-files/
             ##VPC##
      - name: Terraform Init VPC
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/vpc/ && terraform init

      - name: Terraform Plan VPC
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/vpc/ && terraform plan


      - name: Aguardar antes do APPLY
        run: sleep "${{ github.event.inputs.wait-time }}" || sllep "3m"

      - name: Terraform APPLY VPC
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/vpc/ && terraform apply -auto-approve

            ##ECR##
      - name: Terraform Init ECR
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ecr/ && terraform init

      - name: Terraform Plan ECR
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ecr/ && terraform plan


      - name: Aguardar antes do APPLY 
        run: sleep "${{ github.event.inputs.wait-time }}" || sllep "3m"

      - name: Terraform APPLY ECR
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ecr/ && terraform apply -auto-approve

            ##EC2##
      - name: Terraform Init EC2
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ec2/ && terraform init

      - name: Terraform Plan EC2
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ec2/ && terraform plan


      - name: Aguardar antes do APPLY
        run: sleep "${{ github.event.inputs.wait-time }}" || sllep "3m"

      - name: Terraform APPLY EC2
        run: cd ./repository-files/Cloud_infraestrutura/AWS/terraform/ec2/ && terraform apply -auto-approve