name: Terraform Plan - Infra_LAB_Globo
on: push
env: 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCOUNT_ID: $    {{secrets.AWS_ACCOUNT_ID}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  LATEST_IMAGE_TAG: ${{secrets.LATEST_IMAGE_TAG}}

jobs:
  terraform_plan:
    name:  Terraform Plan
    runs-on:  ubuntu-latest
    defaults:
      run:
        shell:  bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name:  Terraform Plan
        run: |
          terraform init
          terraform validate
          terraform plan